### ISSUE TITLE
Formal spec text tracking

### ISSUE THREAD

**Issue by eqrion** [WebAssembly/js-string-builtins#35]
This is a tracking issue for updates to the formal text for phase 4. 

- [x] Merge with upstream wasm3.0 branch to get GC
- [x] Add section defining the 'Builtins' concept
- [x] Add WebAssemblyCompileOptions to WebIDL and thread through compile/instantiation methods
- [x] WebAssembly.Module object gets a slot for an ordered list of builtin groups that are enabled
- [x] 'compile a module' algorithm does an eager import matching step against the builtin groups that are enabled
- [x] 'instantiate a module' algorithm instantiates builtins into hostfuncs and passes them as imports
- [x] WebAssembly.Module.imports() should hide imports that refer to a builtin group
- [x] Add definitions for 'wasm:js-string' function builtins
- [x] Add 'importedStringConstants' to WebAssemblyCompileOptions, define similarly to builtins?

cc @ajklein who was interested in this.

**Comment by eqrion** [comment]
I think we've just about got all of this now.
